name: CI

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  fast-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Determine Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn
          yarn lerna bootstrap
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn coverage:fast
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./coverage.lcov
          env_vars: CI_OS,TEST_TYPE
        env:
          CI_OS: ${{ matrix.os }}
          TEST_TYPE: fast

  slow-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-18.04]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2.3.4
      - name: Windows specific setup
        if: matrix.os == 'windows-latest'
        run: |
          C:\ProgramData\chocolatey\lib\wixtoolset\tools\wix311.exe /install /quiet /norestart
          npm config set node-gyp "$($env:GITHUB_WORKSPACE)\node_modules\node-gyp\bin\node-gyp.js"
      - name: Linux specific setup
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository -y ppa:alexlarsson/flatpak
          sudo rm /etc/apt/sources.list.d/bazel.list
          sudo rm /etc/apt/sources.list.d/mongo*.list
          grep -l opensuse /etc/apt/sources.list.d/* | xargs sudo rm
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends snapcraft flatpak-builder elfutils
          ci/install_runtimes.sh
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Determine Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn
          yarn lerna bootstrap
      - name: Test on Windows
        if: matrix.os == 'windows-latest'
        run: |
          $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
          $env:PATH = $env:PATH + $wixToolsetBinPath
          [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
          if ((Get-Command "light.exe" -ErrorAction SilentlyContinue) -eq $null)
          {
            Write-Host "Unable to find light.exe in your PATH"
          }
          yarn coverage:slow
      - name: Test on macOS/Linux
        if: matrix.os != 'windows-latest'
        run: yarn coverage:slow
        env:
          DEBUG: electron-installer-snap:snapcraft
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./coverage.lcov
          env_vars: CI_OS,TEST_TYPE
        env:
          CI_OS: ${{ matrix.os }}
          TEST_TYPE: slow

  automerge:
    needs: [fast-tests, slow-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # docs:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   needs: [fast-tests, slow-tests]
  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js 12.x
  #       uses: actions/setup-node@v2.1.5
  #       with:
  #         node-version: 12.x
  #     - name: Cache node_modules
  #       uses: actions/cache@v2.1.6
  #       with:
  #         path: node_modules
  #         key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.OS }}-build-${{ env.cache-name }}-
  #           ${{ runner.OS }}-build-
  #           ${{ runner.OS }}-
  #     - name: Deploy docs
  #       run: ci/docs.sh
  #       env:
  #         NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
